### ISSUE TITLE
Installation fails when the steps provided in install.md are followed.

### ISSUE THREAD

**Issue by anvithks** [opensds/orchestration#39]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

/kind bug

**What happened**:
I tried to install orchestration manager by following the steps provided in https://github.com/opensds/orchestration/blob/master/docs/INSTALL.md

the installation failed with following error.

![Screenshot from 2019-05-29 23-54-13](https://user-images.githubusercontent.com/19162717/58607043-9c0b6b00-82bb-11e9-8f58-7132bed7f4aa.png)

**What you expected to happen**:
Orchestration manager should have been installed.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the steps in the install.md file linked above.

**Anything else we need to know?**:

**Environment**:
- Orchestration(release/branch) version: 
- OS (e.g. from /etc/os-release): Ubuntu 16.04.6
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by skdwriting** [comment]
closing
