### ISSUE TITLE
Instance input list object should not have backslashes

### ISSUE THREAD

**Issue by kumarashit** [opensds/orchestration#48]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: Instance listing has backslashes in "input" field
[
    {
        "created_at": "Mon, 03 Jun 2019 12:04:46 GMT",
        "description": null,
        "id": "5cf50e20ebe06301f3faa4e4",
        "input": "{\"ip_addr\": \"192.168.20.67\", \"description\": \"Migration_test_orchestration\", \"srcBucketName\": \"aws-orchestrate\", \"auth_token\": \"gAAAAABc9Q3qklyGA3wnFHBo27z93rUSSDYU-S6X4SGQhTI4hhozKwsqxFvQ2KY-0wVJfIJ6wDQjwiRyFw6-8ALSFAtcZOSNCf8N5xQCisZJHN-Iw6oDWO6xe7jrs0sLWRjlqtlOyDX-Q7eDhBgXxD66BSDYo1sEcJBfOtrLxk25LWZ4HeIUya159aqyh6FrpC08161gw97T\", \"userId\": \"558057c4256545bd8a307c37464003c9\", \"remainSource\": true, \"destBucketName\": \"hw-orchestrate\", \"tenant_id\": \"94b280022d0c4401bcf3b0ea85870519\", \"destBackend\": \"hw-backend\", \"port\": \"8089\", \"name\": \"testmigration\"}",
        "name": "migration-bucket",
        "output": null,
        "service_id": "eecd76dd-f46b-4113-a7ab-9108107a2f3e",
        "status": null,
        "updated_at": "Mon, 03 Jun 2019 12:04:46 GMT",
        "workflow_definition_id": "417de5d9-a8d3-4499-9148-ed56cca15d3b",
        "workflow_source": "opensds.migration-bucket"
    },

**What you expected to happen**: It should be sanitized

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Orchestration(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
PR is raised for it.

**Comment by skdwriting** [comment]
closing
