### ISSUE TITLE
User should be able to re-run an instance

### ISSUE THREAD

**Issue by kumarashit** [opensds/orchestration#53]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
 /kind feature

**What happened**: 

**What you expected to happen**: User should be able to re-run a failed or successful instance

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Orchestration(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
Backlog

**Comment by skdwriting** [comment]
As we discussed, start is there, hence it should be ok. closing this.
