### ISSUE TITLE
Use configuration file for integration with other modules

### ISSUE THREAD

**Issue by joseph-v** [opensds/orchestration#56]
Instead of using credcreator.py for storing configuration,

[./orchestration/connectionmanager/credcreator.py set "St2" "<ST2 Endpoint IP>" "st2admin" "<ST2 Password>"]

add a configuration file.

**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**Comment by skdwriting** [comment]
As discussed, please fix this within RC2 and raise the PR before CAPRI

**Comment by kumarashit** [comment]
PR is raised by @joseph-v
