### ISSUE TITLE
Pass Auth-Token in the Header Request for the service Instance creation

### ISSUE THREAD

**Issue by himanshuvar** [opensds/orchestration#60]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:  For Instance creation, Auth Token is passed in the Request body.

**What you expected to happen**: For Instance creation,  Auth Token is supposed to pass in the Request Header

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Orchestration(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
Must fix
