### ISSUE TITLE
Change Orchestration  Endpoint URL to use correct path

### ISSUE THREAD

**Issue by kumarashit** [opensds/orchestration#74]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
 /kind feature

**What happened**: Temporarily we have changed the url to /orchestration/<tenant_id>/*. This is not THE solution

**What you expected to happen**: We should find out a way to check for URL redirection and the URL should be /v1beta/<tenant_id>/orchestration/*. Temporary fix made under Issue #73 . Should be reverted back

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Orchestration(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kumarashit** [comment]
This is backlog item

**Comment by skdwriting** [comment]
Temporary fix under #73 has been cancelled. Handles the issue with a proper handling in PR #117. Hence this fix not needed.
